<?php

 /*
 * phpMumbleAdmin (PMA), administration panel for murmur (mumble server daemon).
 * Copyright (C) 2010 - 2016, Dadon David, dev.pma@ipnoz.net
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

if (! defined('PMA_STARTED')) { die('You cannot call this script directly !'); }

define('PMA_IMG_MUMBLE_TREE_LINE',      'images/pma/tree_line.png');
define('PMA_IMG_MUMBLE_TREE_MID',       'images/pma/tree_mid.png');
define('PMA_IMG_MUMBLE_TREE_END',       'images/pma/tree_end.png');

define('PMA_IMG_MUMBLE_ROOT',           'images/mumble/mumble.png');
define('PMA_IMG_MUMBLE_CHANNEL',        'images/pma/tree_channel.png');
define('PMA_IMG_MUMBLE_USER',           'images/pma/tree_user.png');

define('PMA_IMG_MUMBLE_LINK_WITH',      'images/pma/tree_link_with.png');
define('PMA_IMG_MUMBLE_LINK_DIRECT',    'images/pma/tree_link_direct.png');
define('PMA_IMG_MUMBLE_LINK_INDIRECT',  'images/pma/tree_link_indirect.png');

define('PMA_IMG_MUMBLE_HOME',           'images/other/home_16.png');
define('PMA_IMG_MUMBLE_AUTH',           'images/mumble/user_auth.png');
define('PMA_IMG_MUMBLE_COMMENT',        'images/mumble/comment.png');
define('PMA_IMG_MUMBLE_REC',            'images/xchat/red_12.png');
define('PMA_IMG_MUMBLE_MIC',            'images/tango/microphone_16.png');
define('PMA_IMG_MUMBLE_PW',             'images/gei/padlock_16.png');
define('PMA_IMG_MUMBLE_TEMP',           'images/tango/clock_16.png');
define('PMA_IMG_MUMBLE_SUPRESSED',      'images/mumble/user_suppressed.png');
define('PMA_IMG_MUMBLE_MUTED',          'images/mumble/user_muted.png');
define('PMA_IMG_MUMBLE_DEAFENED',       'images/mumble/user_deafened.png');
define('PMA_IMG_MUMBLE_SELF_MUTE',      'images/mumble/user_selfmute.png');
define('PMA_IMG_MUMBLE_SELF_DEAF',      'images/mumble/user_selfdeaf.png');
